### ISSUE TITLE
Update website with new README

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl-org.github.io#2]
Heya! I did a bit of an overhaul/cleanup of the README, and the website needs updating. It's a pretty big change, but I don't expect to be doing any more major rewrites for a bit. How should we go about doing this? Do you want me to make the changes and put up a PR, split up the work, or what? :)

@scotttrinh

**Comment by zkat** [comment]
This also raises the question of whether we want to use some sort of .md -> HTML thing to make this process a bit more straightforward? I don't wanna ask anyone to write a whole bunch of HTML to keep things synced with the spec 😅

**Comment by scotttrinh** [comment]
Basing the site on the README was more of a strategy to overcome the blank page problem, and understand what questions to needed answering technically, than any sort of real goal.

If we want to keep a lot of alignment there, I'm happy to work on building out a basic structure that we can copy-paste large chunks of markdown, to lighten the load.

If we want to approach the content strategy from a different direction than the README (for instance, being more example-driven, or diving deeper into usage) than I'm fine with just manually porting over the rest of the new README as filler while we plan that out in more depth.

**Comment by scotttrinh** [comment]
> This also raises the question of whether we want to use some sort of .md -> HTML thing to make this process a bit more straightforward? I don't wanna ask anyone to write a whole bunch of HTML to keep things synced with the spec 😅 

Luckily 11ty can handle Markdown just fine, I've just opted for regular HTML to enable more styling, but the tailwind typography plugin was specifically designed to just make plain Markdown look good, so it should be easy enough to just do most of this as Markdown.

**Comment by zkat** [comment]
I think whatever content strategy is most convenient is best! The website only needs a couple of things: A page for the README, and a page for the spec. I can't think of anything else it might need right now? Some obvious links back to the various Github repos would be nice, too. That's about it?

**Comment by scotttrinh** [comment]
Makes sense to me! I can pretty easily get the latest README changes up in Markdown over the weekend, and think a bit about design now that the content is feeling fleshed out. Let me know if you have anything in mind design-wise, even if it's just some links, otherwise, I'll keep it pretty minimal and focus on the spacing/rhythm and logical flow.

**Comment by zkat** [comment]
Pretty sure this is done now!
