### ISSUE TITLE
Integrate new logo/favicon

### ISSUE THREAD

**Issue by zkat** [kdl-org/kdl-org.github.io#6]

**Comment by scotttrinh** [comment]
Probably want to use an SVG, if that's not too much trouble to get to.

/cc @timmybytes

**Comment by timmybytes** [comment]
@scotttrinh Absolutely, I’m working on that currently! Because of the way typography outline strokes are converted when exporting, SVGs end up a bit mucked up with the current design in Figma. I should have a fix soon, and plan to submit a new PR once they’re of sufficient quality.

**Comment by zkat** [comment]
I've merged the PR with the SVG stuff 👍🏻

**Comment by scotttrinh** [comment]
Thanks @timmybytes and @zkat, I can take this on!

**Comment by scotttrinh** [comment]
🙈 My change didn't add the favicon, so I'll reopen this and get to that soon!

**Comment by scotttrinh** [comment]
@timmybytes Thanks for the awesome work on the logo! Favicons are live now.

Question @zkat , do you think we should remove the favicon graphic files from this repo to avoid having two places where they are? Is the much value in having them here with the spec? Seems like it makes sense for the branding graphics to maybe stay here.

**Comment by zkat** [comment]
I think it's OK to keep them duplicated for now!
