### ISSUE TITLE
nit - how to change this rendering on the main page?

### ISSUE THREAD

**Issue by ericsampson** [kdl-org/kdl-org.github.io#9]
I am _not_ a front-end dev in any sense, other wise I'd submit a PR. I took a quick look around but didn't see how to change this behavior:

I find these backticks distracting, because it makes it harder to understand what is syntax. Is there something that could be tweaked so that it isn't generated this way?

![image](https://user-images.githubusercontent.com/1183853/103811067-ef11dc00-5021-11eb-95e2-402632b82a93.png)

**Comment by zkat** [comment]
@scotttrinh turns out I can just transfer it 😅

**Comment by ericsampson** [comment]
Thanks @scotttrinh I didn't realize there was a separate repo for the website!! :)

**Comment by ericsampson** [comment]
Looks like someone opened this as a bug report, and also provided a workaround :)

https://github.com/tailwindlabs/tailwindcss-typography/issues/123

**Comment by scotttrinh** [comment]
Thanks for the link! Probably want some styling similar to GitHub here, so I can also add a subtle background color, too.
